# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-09-22 20:14
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OllieUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=64)),
                ('zip_code', models.CharField(max_length=10)),
                ('email', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='PetInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dog_name', models.CharField(max_length=64)),
                ('lineage', models.CharField(choices=[(b'single breed', b'single breed'), (b'two breeds', b'two breeds'), (b'unknown mix', b'unknown mix')], max_length=12)),
                ('primary_breed', models.CharField(max_length=50)),
                ('secondary_breed', models.CharField(max_length=50)),
                ('sex', models.CharField(choices=[(b'male', b'male'), (b'female', b'female')], max_length=6)),
                ('sterilized', models.NullBooleanField()),
                ('birth_month', models.CharField(choices=[(1, b'Jan'), (2, b'Feb'), (3, b'Mar'), (4, b'Apr'), (5, b'May'), (6, b'Jun'), (7, b'Jul'), (8, b'Aug'), (9, b'Sep'), (10, b'Oct'), (11, b'Nov'), (12, b'Dec')], max_length=2)),
                ('birth_year', models.IntegerField()),
                ('activity_level', models.CharField(choices=[(b'lazy', b'lazy'), (b'active', b'active'), (b'hyper', b'hyper')], max_length=6)),
                ('weight', models.IntegerField()),
                ('body_type', models.CharField(choices=[(b'skinny', b'skinny'), (b'ideal', b'ideal'), (b'chubby', b'chubby')], max_length=6)),
                ('primary_protein', models.CharField(max_length=20)),
                ('allergies', models.TextField()),
                ('dry_food', models.NullBooleanField()),
                ('wet_food', models.NullBooleanField()),
                ('raw_food', models.NullBooleanField()),
                ('freeze_dried_food', models.NullBooleanField()),
                ('home_cooked_food', models.NullBooleanField()),
                ('fresh_food', models.NullBooleanField()),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pets', to='ollie.OllieUser')),
            ],
        ),
    ]
