# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-09-23 00:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ollie', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='petinfo',
            name='birth_month',
            field=models.CharField(choices=[(b'Jan', b'Jan'), (b'Feb', b'Feb'), (b'Mar', b'Mar'), (b'Apr', b'Apr'), (b'May', b'May'), (b'Jun', b'Jun'), (b'Jul', b'Jul'), (b'Aug', b'Aug'), (b'Sep', b'Sep'), (b'Oct', b'Oct'), (b'Nov', b'Nov'), (b'Dec', b'Dec')], max_length=3),
        ),
    ]
