# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-09-23 00:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ollie', '0002_updates_birth_month_choices'),
    ]

    operations = [
        migrations.AlterField(
            model_name='petinfo',
            name='lineage',
            field=models.CharField(choices=[(b'single breed', b'single breed'), (b'mix of two breeds', b'mix of two breeds'), (b'unknown mix', b'unknown mix')], max_length=17),
        ),
    ]
